package org.cite.dto;

public enum ResponseStatus {
    SUCCESS,
    EMPLOYEE_NOT_FOUND,
    EMPLOYEE_NOT_CREATED,
    EMPLOYEE_CANNOT_BE_UPDATED,
    ATTRIBUTE_NOT_CREATED,
    ATTRIBUTE_CAN_NOT_BE_DELETED,
    ATTRIBUTE_NOT_FOUND
}